### ISSUE TITLE
Ability to use docker compose

### ISSUE THREAD

**Issue by bastiitsab** [luke-browning/pdf-web-edit#53]
As I know there needs to be a published package to use docker compose. Would love to use that instead of plain docker. If there is another way -> happy to learn :)

**Comment by DanielHabenicht** [comment]
You can have a look here: 
https://github.com/DanielHabenicht/fork.pdf-web-edit/blob/v0.9.2/docker-compose.yml

Just replace the build option with the image: 

```yml
version: '3'
services:
  pdfedit:
    image: lbrowning/pdf-web-edit
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./volumes/config/:/config/
      - ./volumes/inbox/:/inbox
      - ./volumes/outbox/:/outbox
      - ./volumes/archive/:/archive
#    user: '1000:1000'

```
